version: "1.0"
stages:
   - clone
   - build
   - deploy
steps:
  clone:
    title: Cloning Repository
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    registry: dockerhub
    image_name: 'anaisurlichs/rookout-example'
    working_directory: "./${{CF_REPO_NAME}}"
    tag: '1.0.0'
    dockerfile: Dockerfile
  deploy:
    title: Deploying to Testing
    type: helm
    working_directory: "./${{CF_REPO_NAME}}"
    stage: deploy
    arguments:
      action: upgrade
      chart_name: "charts/rookout-example"
      release_name: "${{CF_REPO_NAME}}"
      helm_version: "${{HELM_VERSION}}"
      kube_context: anais-cluster@codefresh-sa
      namespace: testing
      custom_values:
        - "rookout_token=${{ROOKOUT_TOKEN}}"
        - "git_commit=codefresh-demo"
        - "origin=tutorial-python"
    when:
      branch:
          only:
            - codefresh-demo  