version: '2'
services:
  tutorial-python:
    container_name: pythontodoapp
    restart: always
    build: .
    environment:
      - ROOKOUT_AGENT_HOST=rookout-agent
    ports:
      - "5000:5000"
    links:
      - rookout-agent
  rookout-agent:
    container_name: rookout-agent
    image: rookout/agent
    environment:
      - ROOKOUT_TOKEN=$ROOKOUT_TOKEN
    ports:
      - "7486:7486"
